"use strict";
let Lname;
Lname = 'Vidisha';
let newname = Lname.toLowerCase();
console.log(newname);
//Lname = 10;
let age;
age = 20;
let dob = "25";
let result = parseInt(dob);
let isValid;
console.log(isValid);
